version: "3"

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 4234:80
    networks:
      - default

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - default

  wordpress:
    build: ./requirements/wordpress
    networks:
      - default

networks:
  default:
    name: server
  # driver: bridge #optional

volumes:
  db_data: